### ISSUE TITLE
Responsive Menu doesn't open

### ISSUE THREAD

**Issue by hereischris** [timcreative/light-bootstrap-dashboard-pro#1]
Hey Guys,

I recently bought the dashboard pro and unfortunately it seems, that the responsive behaviour (off-canvas) of the main menu isn't properly implemented. It simply doesn't open when you click on it.
It seems to me that it isn't implemented. In the free version, it works.

Unfortunately, I can't provide you any code because it's a closed dev environment.
But have a look at the Doc/Sample files of the dashboard pro version. The responsive menu isn't working their either.
The dashboard is good work anyway :-)

**Comment by alexandru-paduraru** [comment]
@hereischris thank you for using our product. We test the off canvas on chrome dev tools and it is working fine for the archive that is on creative-tim.com. 

Can you please give us more details about the product that you are developing? Like what framework you use, what programming language, what device you used etc. Then we will check which are the possible problems. Please check the video with the test that I've did: http://sendvid.com/dgvzdp4j

**Comment by hereischris** [comment]
Now I've investigated a little further. Is it possible, that the file: /assets/js/light-bootstrap-dashboard.js is lacking in the download?

**Comment by alexandru-paduraru** [comment]
I've checked again the archive and all the files are there. Can you please tell me which development framework are you using? This is the only way that we will find the issue.

Best,
Alex

**Comment by hereischris** [comment]
What do you mean by development framework? 
On the client side there is nothing but your dashboard plus some jquery/vanilla javascript.
Anyway, i think im missing a javascript file. Maybe I messed it up :-)
Would it be possible to provide me with another download?
The email chris.siehler (at) gmail.com, to compare with purchases.

many thanks

**Comment by alexandru-paduraru** [comment]
@hereischris I was thinking at frameworks like Ruby on Rails, Zend etc some of them have a different assets pipeline and you need to manually add our CSS and JS in a specific order because there are dependecies between those files.

I sent the archive to your email, please let me know if everything is fine. BTW you can also download the latest updates on creative-tim.com/downloads

Keep in touch,
Alex

**Comment by SlovaDev** [comment]
@alexandru-paduraru Have been having the same issue with lbd. You mentioned, "you need to manually add our CSS and JS in a specific order because there are dependencies between those files."

What is this order?
Thanks for your excellent product,
Grant

**Comment by alexandru-paduraru** [comment]
@SlovaDev, you need add the files exactly in this order:

<img width="1061" alt="screen shot 2017-05-11 at 23 32 40" src="https://cloud.githubusercontent.com/assets/2517758/25970678/25e4f0de-36a2-11e7-997f-172a26fd02e8.png">

So jQuery first, bootstrap, plugins etc. because bootstrap needs jQuery, other plugins need Bootstrap, other need jQuery. Makes sense?

Best,
Alex

**Comment by lizrosenshine** [comment]
Hello,

I am having the same issue.  I noticed the template file is missing from the pro version.  Something seems awry.  After a night of toying, and finally finding this post, I noticed the script call to include jquery doesn't seem to be in the template files.  Once added, it worked well.  Should I change this to the text call you have?  

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="js/scripts.js"></script>

**Comment by alexandru-paduraru** [comment]
@lizrosenshine as we've talked via support, the actual template file is in `examples/plain-page.html`. We will do that change on the next release.

Best,
Alex

**Comment by dczukoski** [comment]
I was going to try to use this in rails. Any advise on incorporating into its pipeline?
