### ISSUE TITLE
Alert only works inside card container

### ISSUE THREAD

**Issue by gpedro** [timcreative/light-bootstrap-dashboard-pro#14]
without card
![without card](https://cloud.githubusercontent.com/assets/2898638/19833572/f4bc787a-9e1b-11e6-8537-ab8cf82f25fc.png)

with card
![with card](https://cloud.githubusercontent.com/assets/2898638/19833571/f4baab4e-9e1b-11e6-8056-26eccde8ecf7.png)

**Comment by gpedro** [comment]
# how to solve

_alerts.scss
```
   // line 8
    .container &, .container-fluid &{
        border-radius: 4px;
        position: relative;
    }
```

**Comment by alexandru-paduraru** [comment]
@gpedro thank you for using our product and also for the fix. You're right, it seems the alerts are having an issue. We will update the core product too with your fix.

Please let us know if we can help you with anything else.

All the best,
Alex

**Comment by gpedro** [comment]
@alexandru-paduraru yo! thanks you for replying.
I don't if your workflow allow this, but would be great if your team use modern workflow:
- bower as dependency manager
- gulp as task-runner

anyway, thanks again for fast replying <3

**Comment by alexandru-paduraru** [comment]
@gpedro thank you for the idea, we've got this idea with Bower from other users too, and we started to add it for the free products when we update them. So in the future there will be bower dependencies also on the premium products. 

Keep in touch,
Alex
