### ISSUE TITLE
ipad mini nav scrolling

### ISSUE THREAD

**Issue by gmalkoun** [timcreative/light-bootstrap-dashboard-pro#2]
Hi, seems to be an issue when on a mini ipad that has the nav open, you cant scroll. Seems to work fine on a iphone

**Comment by alexandru-paduraru** [comment]
Hi @gmalkoun, thank you for using our product. We checked the nav open on iPad mini and we couldn't find the problem, please see this video: http://sendvid.com/xg8s6q6p 

Can you give us more details so we can reproduce your environment.

Best,
Alex
