### ISSUE TITLE
Modal not clickable in mobile view

### ISSUE THREAD

**Issue by oleg-kiviljov** [timcreative/light-bootstrap-dashboard-pro#24]
Cannot click on modal when in mobile view

Example can be seen here:
https://www.dropbox.com/s/60t8anq6quagfgu/Screenshot%202017-05-16%2013.55.32.png?dl=0

**Comment by alexandru-paduraru** [comment]
@oleg-kiviljov thank you for using our product. Please go to `assets/css/light-bootstrap-dashboard.css` on line 8509 and where is the class `.main-panel` and remove this code:

```
    -webkit-transform: translate3d(0px, 0, 0);
    -moz-transform: translate3d(0px, 0, 0);
    -o-transform: translate3d(0px, 0, 0);
    -ms-transform: translate3d(0px, 0, 0);
    transform: translate3d(0px, 0, 0); 
```
Then everything will work fine.

<img width="1533" alt="screen shot 2017-05-19 at 12 50 14" src="https://cloud.githubusercontent.com/assets/2517758/26242669/ed6b4abe-3c91-11e7-94ae-1d71478a07e6.png">

Best,
Alex

**Comment by oleg-kiviljov** [comment]
@alexandru-paduraru thank you for the support, worked perfectly
