### ISSUE TITLE
Alignment not correct with bootstrap-tables and fixed height

### ISSUE THREAD

**Issue by creative-timzye** [timcreative/light-bootstrap-dashboard-pro#3]
When using light-bootstrap-dashboard-pro in combination with data tables (bootstrap-table) and set a fixed height, the alignment of the th is not the same as with td, so the column names are not in the same alignment as the column data.
This only happens with fixed height. When set with pagination, the alignment is correct.

Screenshot with pagination:
![lg-app - wareneingang 2016-02-24 11-00-32](https://cloud.githubusercontent.com/assets/17433871/13281910/ba11e550-dae6-11e5-864d-f42129c8edb2.png)

Screenshot with fixed height:
![lg-app - wareneingang 2016-02-24 11-01-00](https://cloud.githubusercontent.com/assets/17433871/13281923/c4760cec-dae6-11e5-894e-589d7ea13c95.png)

The data columns are offset by the width of the vertical scrollbar.

When using bootstrap-table without light-bootstrap-dashboard-pro the alignment is correct:
![wareneingang prufen 2016-02-24 11-09-32](https://cloud.githubusercontent.com/assets/17433871/13282006/1e52695e-dae7-11e5-84ef-afd3c1faf205.png)

**Comment by alexandru-paduraru** [comment]
@creative-timzye thank you for the information. We've checked and it looks like we add some padding to the first th of the header to align the checkboxes. Since there are no checkboxes the property is moving the header but it's not moving the cells. So please go to the end of light-bootstrap-dashboard.css and add this property:

    .card .fixed-table-header .table thead th:first-child {
        padding-left: 0;
    }

This will fix the issue.

**Comment by creative-timzye** [comment]
@alexandru-paduraru Thank you for this code snippet. This fixes the offset and the columns are aligned correctly.

**Comment by alexandru-paduraru** [comment]
@creative-timzye you're welcome! :-)

**Comment by creative-timzye** [comment]
@alexandru-paduraru I think, you also have to add `.card .fixed-table-body .table thead th:first-child {
    padding-left: 0;
}` to make proper alignement with pagination true and without fixed-height. Otherwise the th for first column is offset to the right.

**Comment by alexandru-paduraru** [comment]
@creative-timzye yes you're right, we didn't check the variation without having the fixed height. We will add this in the next release. Thank you so much!
