### ISSUE TITLE
Popovers are covered by table header when using data tables / bootstrap-table

### ISSUE THREAD

**Issue by creative-timzye** [timcreative/light-bootstrap-dashboard-pro#4]
When using data tables / bootstrap-table in combination with the bootstrap-table extension editable ([https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions/editable](url)) the popover is not visible / covered by the table head. See screenshots:

Here it is OK (I added drop-shadow to the popover for better visibility):
![lg-app - wareneingang 2016-02-24 17-38-39](https://cloud.githubusercontent.com/assets/17433871/13292817/8c55fd54-db1d-11e5-8729-2bcf8af2b23d.png)

Here it is partly covered:
![lg-app - wareneingang 2016-02-24 17-39-57](https://cloud.githubusercontent.com/assets/17433871/13292842/a75a6856-db1d-11e5-8ffa-1c97b3adfa69.png)

Here it is totally covered:
![lg-app - wareneingang 2016-02-24 17-40-35](https://cloud.githubusercontent.com/assets/17433871/13292857/bf22dc5c-db1d-11e5-945b-5cf43d801e6e.png)

The data-table is with fixed height.

**Comment by alexandru-paduraru** [comment]
@creative-timzye We've checked and couldn't replicate the issue. We added the editable extension and everything seems to work fine. Check these screens:

<img width="1440" alt="screen shot 2016-02-25 at 16 17 26" src="https://cloud.githubusercontent.com/assets/2517758/13322150/b1c1b48e-dbdb-11e5-9b30-b88328e9d76e.png">

<img width="1440" alt="screen shot 2016-02-25 at 16 17 11" src="https://cloud.githubusercontent.com/assets/2517758/13322154/b5259032-dbdb-11e5-989b-833b380cb62e.png">

If I have to guess the issue is caused by the **overflow: scroll** property of the table, the solution that we gave you for scrolling inside the table. It is hiding everything that is outside of the table so you can scroll inside.  So as a solution to this I recommend you to use the **data-editable-mode="inline"** for each **th**. This will give the same functionality but inline, so you will not have any issues with the Scrollable part that you need.

Please let me know if that was working fine.

**Comment by creative-timzye** [comment]
@alexandru-paduraru To replicate the issue you have to use a bootstrap-table with fixed-height and the overflow: scroll you gave me.
I tried **data-editable-mode="inline"** which works, but it is not a "great" solution.  **data-editable-mode="popup"** looks a lot better and more stylish. We are using ligh-bootstrap-dashboard-pro because it has a great look.
Can you find a better solution, so we can still work with fixed-height and popup?
Thanks!!

**Comment by alexandru-paduraru** [comment]
@creative-timzye I will follow the same configuration that you have. We will think about a solution but from the experience, for that situation when you have an element which have the overflow:scroll or overflow:hidden, nothing cannot go out of it, that's a basic rule that the browser respect. The current 2 options are: 

1. you use the table with pagination, without scrolling and the popup will appear
2. you use the table with scroll and fixed height and you use the edit inline.

I hope we will find a trick for your case.

Keep in touch,
Alex

**Comment by alexandru-paduraru** [comment]
@creative-timzye we tried different tricks in order to make a combination between the options 1 and 2 and unfortunately it is not possible to have the table with scroll area and to have inside it the popup which appear outside of the scrolling area. The browser doesn't allow this.

We added in the latest update V1.2 some bug fixes which include also the fixes for the table with fixed height which was moving the labels. We also added a scrollbar library for Windows users, so the ugly scrollbar is not visible anymore.

Hope you understand the situation. If you have any other ideas for the table please let us know, we would be glad to test them.

Best,
Alex

**Comment by novamix** [comment]
how do you have installed the plugin ?, because I do not get it to work.

**Comment by alexandru-paduraru** [comment]
@novamix the plugin doesn't need to be "installed", it is just a plain JS file: here is the full documentation -> http://bootstrap-table.wenzhixin.net.cn/ And you can find how we initialized it in your downlaoded archive examples/tables/datatable.html

Please let us know if you found the plugin. Or please let us know what is not working.

Best,
Alex

**Comment by novamix** [comment]
I add the code on footer and add 

```
<link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script src="extensions/editable/bootstrap-table-editable.js"></script>
```
and the column 

`<th data-field="name" data-editable="true" data-sortable="true">Name</th>`

and finally my all code


`<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard PRO by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    
    <link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />

    
    <link href="../../assets/css/light-bootstrap-dashboard.css" rel="stylesheet"/>

    
    <link href="../../assets/css/demo.css" rel="stylesheet" />

    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>

    
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="orange" data-image="../../assets/img/full-screen-image-3.jpg">
        

        <div class="logo">
            <a href="http://www.creative-tim.com" class="logo-text">
                Creative Tim
            </a>
        </div>

    	<div class="sidebar-wrapper">

            <div class="user">
                <div class="photo">
                    <img src="../../assets/img/default-avatar.png" />
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                        Tania Andrew
                        <b class="caret"></b>
                    </a>
                    <div class="collapse" id="collapseExample">
                        <ul class="nav">
                            <li><a href="#">My Profile</a></li>
                            <li><a href="#">Edit Profile</a></li>
                            <li><a href="#">Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <ul class="nav">
                <li>
                    <a href="../dashboard.html">
                        <i class="pe-7s-graph"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li>
                    <a data-toggle="collapse" href="#componentsExamples">
                        <i class="pe-7s-plugin"></i>
                        <p>Components
                           <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="componentsExamples">
                        <ul class="nav">
                            <li><a href="../components/buttons.html">Buttons</a></li>
                            <li><a href="../components/grid.html">Grid System</a></li>
                            <li><a href="../components/icons.html">Icons</a></li>
                            <li><a href="../components/notifications.html">Notifications</a></li>
                            <li><a href="../components/panels.html">Panels</a></li>
                            <li><a href="../components/sweet-alert.html">Sweet Alert</a></li>
                            <li><a href="../components/typography.html">Typography</a></li>
                        </ul>
                    </div>
                </li>

                <li>
                    <a data-toggle="collapse" href="#formsExamples">
                        <i class="pe-7s-note2"></i>
                        <p>Forms
                           <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="formsExamples">
                        <ul class="nav">
                            <li><a href="../forms/regular.html">Regular Forms</a></li>
                            <li><a href="../forms/extended.html">Extended Forms</a></li>
                            <li><a href="../forms/validation.html">Validation Forms</a></li>
                            <li><a href="../forms/wizard.html">Wizard</a></li>
                        </ul>
                    </div>
                </li>

                <li class="active">
                    <a data-toggle="collapse" href="#tablesExamples" aria-expanded="true">
                        <i class="pe-7s-news-paper"></i>
                        <p>Tables
                           <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse in" id="tablesExamples">
                        <ul class="nav">
                            <li><a href="regular.html">Regular Tables</a></li>
                            <li><a href="extended.html">Extended Tables</a></li>
                            <li class="active"><a href="datatable.html">Data Tables</a></li>
                        </ul>
                    </div>
                </li>

                <li>
                    <a data-toggle="collapse" href="#mapsExamples">
                        <i class="pe-7s-map-marker"></i>
                        <p>Maps
                           <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="mapsExamples">
                        <ul class="nav">
                            <li><a href="../maps/google.html">Google Maps</a></li>
                            <li><a href="../maps/vector.html">Vector Maps</a></li>
                            <li><a href="../maps/fullscreen.html">Full Screen Map</a></li>
                        </ul>
                    </div>
                </li>

                <li>
                    <a href="../charts.html">
                        <i class="pe-7s-graph1"></i>
                        <p>Charts</p>
                    </a>
                </li>

                <li>
                    <a href="../calendar.html">
                        <i class="pe-7s-date"></i>
                        <p>Calendar</p>
                    </a>
                </li>

                <li>
                    <a data-toggle="collapse" href="#pagesExamples">
                        <i class="pe-7s-gift"></i>
                        <p>Pages
                           <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse" id="pagesExamples">
                        <ul class="nav">
                            <li><a href="../pages/login.html">Login Page</a></li>
                            <li><a href="../pages/register.html">Register Page</a></li>
                            <li><a href="../pages/lock.html">Lock Screen Page</a></li>
                            <li><a href="../pages/user.html">User Page</a></li>
                            <li><a href="#">More coming soon...</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">

                    <form class="navbar-form navbar-left navbar-search-form" role="search">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            <input type="text" value="" class="form-control" placeholder="Search...">
                        </div>
                    </form>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="../charts.html">
                                <i class="fa fa-line-chart"></i>
                                <p>Stats</p>
                            </a>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-gavel"></i>
                                <p class="hidden-md hidden-lg">
                                    Actions
                                    <b class="caret"></b>
                                </p>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Create New Post</a></li>
                                <li><a href="#">Manage Something</a></li>
                                <li><a href="#">Do Nothing</a></li>
                                <li><a href="#">Submit to live</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Another Action</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="notification">5</span>
                                <p class="hidden-md hidden-lg">
    								Notifications
    								<b class="caret"></b>
    							</p>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                            </ul>
                        </li>

                        <li class="dropdown dropdown-with-icons">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-list"></i>
                                <p class="hidden-md hidden-lg">
    								More
    								<b class="caret"></b>
    							</p>
                            </a>
                            <ul class="dropdown-menu dropdown-with-icons">
                                <li>
                                    <a href="#">
                                        <i class="pe-7s-mail"></i> Messages
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="pe-7s-help1"></i> Help Center
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="pe-7s-tools"></i> Settings
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">
                                        <i class="pe-7s-lock"></i> Lock Screen
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="text-danger">
                                        <i class="pe-7s-close-circle"></i>
                                        Log out
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>



        <div class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">

                            <div class="toolbar">
                                
                            </div>

                            <table id="bootstrap-table" class="table">
                                <thead>
                                    <th data-field="state" data-checkbox="true"></th>
                                    <th data-field="id" class="text-center">ID</th>
                                	<th data-field="name" data-editable="true" data-sortable="true">Name</th>
                                	<th data-field="salary" data-sortable="true">Salary</th>
                                	<th data-field="country" data-sortable="true">Country</th>
                                	<th data-field="city">City</th>
                                	<th data-field="actions" class="td-actions text-right" data-events="operateEvents" data-formatter="operateFormatter">Actions</th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td></td>
                                    	<td>1</td>
                                    	<td>Dakota Rice</td>
                                    	<td>$36,738</td>
                                    	<td>Niger</td>
                                    	<td>Oud-Turnhout</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>2</td>
                                    	<td>Minerva Hooper</td>
                                    	<td>$23,789</td>
                                    	<td>Curaçao</td>
                                    	<td>Sinaai-Waas</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>3</td>
                                    	<td>Sage Rodriguez</td>
                                    	<td>$56,142</td>
                                    	<td>Netherlands</td>
                                    	<td>Baileux</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>4</td>
                                    	<td>Philip Chaney</td>
                                    	<td>$38,735</td>
                                    	<td>Korea, South</td>
                                    	<td>Overland Park</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>5</td>
                                    	<td>Doris Greene</td>
                                    	<td>$63,542</td>
                                    	<td>Malawi</td>
                                    	<td>Feldkirchen in Kärnten</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>6</td>
                                    	<td>Mason Porter</td>
                                    	<td>$78,615</td>
                                    	<td>Chile</td>
                                    	<td>Gloucester</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>7</td>
                                    	<td>Alden Chen</td>
                                    	<td>$63,929</td>
                                    	<td>Finland</td>
                                    	<td>Gary</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>8</td>
                                    	<td>Colton Hodges</td>
                                    	<td>$93,961</td>
                                    	<td>Nicaragua</td>
                                    	<td>Delft</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>9</td>
                                    	<td>Illana Nelson</td>
                                    	<td>$56,142</td>
                                    	<td>Heard Island</td>
                                    	<td>Montone</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>10</td>
                                    	<td>Nicole Lane</td>
                                    	<td>$93,148</td>
                                    	<td>Cayman Islands</td>
                                    	<td>Cottbus</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>11</td>
                                    	<td>Chaim Saunders</td>
                                    	<td>$5,502</td>
                                    	<td>Romania</td>
                                    	<td>New Quay</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>12</td>
                                    	<td>Josiah Simon</td>
                                    	<td>$50,265</td>
                                    	<td>Christmas Island</td>
                                    	<td>Sint-Jans-Molenbeek</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>13</td>
                                    	<td>Ila Poole</td>
                                    	<td>$67,413</td>
                                    	<td>Montenegro</td>
                                    	<td>Pontevedra</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>14</td>
                                    	<td>Shana Mejia</td>
                                    	<td>$58,566</td>
                                    	<td>Afghanistan</td>
                                    	<td>Ballarat</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>15</td>
                                    	<td>Lana Ryan</td>
                                    	<td>$64,151</td>
                                    	<td>Martinique</td>
                                    	<td>Portobuffolè</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>16</td>
                                    	<td>Daquan Bender</td>
                                    	<td>$91,906</td>
                                    	<td>Sao Tome and Principe</td>
                                    	<td>Walhain-Saint-Paul</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>17</td>
                                    	<td>Connor Wagner</td>
                                    	<td>$86,537</td>
                                    	<td>Germany</td>
                                    	<td>Solihull</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>18</td>
                                    	<td>Boris Horton</td>
                                    	<td>$35,094</td>
                                    	<td>Laos</td>
                                    	<td>Saint-Mard</td>
                                    	<td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                    	<td>19</td>
                                    	<td>Winifred Ryan</td>
                                    	<td>$64,436</td>
                                    	<td>Ireland</td>
                                    	<td>Ronciglione</td>
                                    	<td></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div> 
                </div> 

            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; 2016 <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>


    </div>
</div>


</body>

    
    <script src="../../assets/js/jquery.min.js" type="text/javascript"></script>
    <script src="../../assets/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../../assets/js/bootstrap.min.js" type="text/javascript"></script>


	
	<script src="../../assets/js/jquery.validate.min.js"></script>

	
	<script src="../../assets/js/moment.min.js"></script>

    
    <script src="../../assets/js/bootstrap-datetimepicker.js"></script>

    
    <script src="../../assets/js/bootstrap-selectpicker.js"></script>

	
	<script src="../../assets/js/bootstrap-checkbox-radio-switch-tags.js"></script>

	
	<script src="../../assets/js/chartist.min.js"></script>

    
    <script src="../../assets/js/bootstrap-notify.js"></script>

    
	<script src="../../assets/js/sweetalert2.js"></script>

    
	<script src="../../assets/js/jquery-jvectormap.js"></script>

    
    <script src="https://maps.googleapis.com/maps/api/js"></script>

	
    <script src="../../assets/js/jquery.bootstrap.wizard.min.js"></script>

    
    <script src="../../assets/js/bootstrap-table.js"></script>

    
    <script src="../../assets/js/fullcalendar.min.js"></script>

    
	<script src="../../assets/js/light-bootstrap-dashboard.js"></script>

	
	<script src="../../assets/js/demo.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script src="../../assets/js/editable-table.js"></script>


    <script type="text/javascript">
        var $table = $('#bootstrap-table');

        function operateFormatter(value, row, index) {
            return [
                '<a rel="tooltip" title="View" class="btn btn-simple btn-info btn-icon table-action view" href="javascript:void(0)">',
                    '<i class="fa fa-image"></i>',
                '</a>',
                '<a rel="tooltip" title="Edit" class="btn btn-simple btn-warning btn-icon table-action edit" href="javascript:void(0)">',
                    '<i class="fa fa-edit"></i>',
                '</a>',
                '<a rel="tooltip" title="Remove" class="btn btn-simple btn-danger btn-icon table-action remove" href="javascript:void(0)">',
                    '<i class="fa fa-remove"></i>',
                '</a>'
            ].join('');
        }

        $().ready(function(){
            window.operateEvents = {
                'click .view': function (e, value, row, index) {
                    info = JSON.stringify(row);

                    swal('You click view icon, row: ', info);
                    console.log(info);
                },
                'click .edit': function (e, value, row, index) {
                    info = JSON.stringify(row);

                    swal('You click edit icon, row: ', info);
                    console.log(info);
                },
                'click .remove': function (e, value, row, index) {
                    console.log(row);
                    $table.bootstrapTable('remove', {
                        field: 'id',
                        values: [row.id]
                    });
                }
            };

            $table.bootstrapTable({
                toolbar: ".toolbar",
                clickToSelect: true,
                showRefresh: true,
                search: true,
                showToggle: true,
                showColumns: true,
                pagination: true,
                searchAlign: 'left',
                pageSize: 8,
                clickToSelect: false,
                pageList: [8,10,25,50,100],

                formatShowingRows: function(pageFrom, pageTo, totalRows){
                    //do nothing here, we don't want to show the text "showing x of y from..."
                },
                formatRecordsPerPage: function(pageNumber){
                    return pageNumber + " rows visible";
                },
                icons: {
                    refresh: 'fa fa-refresh',
                    toggle: 'fa fa-th-list',
                    columns: 'fa fa-columns',
                    detailOpen: 'fa fa-plus-circle',
                    detailClose: 'fa fa-minus-circle'
                }
            });

            //activate the tooltips after the data table is initialized
            $('[rel="tooltip"]').tooltip();

            $(window).resize(function () {
                $table.bootstrapTable('resetView');
            });


        });

    </script>

</html>
`

**Comment by alexandru-paduraru** [comment]
@novamix on the Full Code I see that you added the CSS for the X-editable inside the <head> </head> but you didn't add it in the javascript section. Please add it like this:

1.

<script src="../../assets/js/bootstrap-table.js"></script>

2.
<script src="extensions/editable/bootstrap-table-editable.js"></script>

3.
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>

You can see in this example how the files are called added: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/extensions/editable.html

Please let us know if that was working.

Best,
Alex

**Comment by novamix** [comment]
Hello, now works, thanks.

**Comment by husnixs** [comment]
I'm using this and work prefectly

`"fnDrawCallback": function ( oSettings ) {
            
            $(".edit").editable({
                mode : 'popup',
                container: 'body',
                emptytext : '-',
                ajaxOptions : {
                    type : 'post'
                },
                success: function() {
                    //
                }
            });
}`
