### ISSUE TITLE
Missing Sweetalert feature: inputbox

### ISSUE THREAD

**Issue by oliverhermanni** [timcreative/light-bootstrap-dashboard-pro#5]
Hey, is there a chance you'll add the inputbox in SweetAlert? It seems to be missing. It would be very helpful as I'm using two modal dialogs at the moment.

**Comment by alexandru-paduraru** [comment]
@oliverhermanni thank you for the suggestion. We checked and it looks like the version of the plugin that is inside LBD Pro is not accepting the "input" property. I was spending a couple of hours trying to upgrade the plugin but there are more CSS conflicts than what I anticipated so I cannot give you a "quick fix" now. 

We will add the new plugin in the next update of LBD Pro, we have a new update, which is fixing other issues, prepared for 15-18 March. Hope you understand the situation.

Keep in touch,
Alex

**Comment by oliverhermanni** [comment]
Yeah, no problem. :) The two modal dialogs are okay right now. Can't wait to see the update.

And can't wait less to show you guys, what I'm working on with LBD Pro. ^_^

**Comment by alexandru-paduraru** [comment]
@oliverhermanni We are curious to see what you've built too :D

**Comment by alexandru-paduraru** [comment]
@oliverhermanni this was added in the V1.2 update. Please login on creative-tim.com and download it. 

Thank you!
