### ISSUE TITLE
Mobile Sidebar bottom items not available on iPhone

### ISSUE THREAD

**Issue by nblake989** [timcreative/light-bootstrap-dashboard-pro#6]
It appears that in my implementation and the LBDP Live Preview, the lowest item in the sidebar menu when on the right side (in SM and XS grids) are not available for selection or clicking due to the safari native navigation bar covering the bottom.

This behavior is not seen in a chrome device inspector on desktop, only in the iPhone device or device simulator.

Perhaps blank space is needed at the bottom of the page or perhaps a meta tag to help handle mobile device browsers?

**Comment by nblake989** [comment]
![simulator screen shot mar 29 2016 10 02 03 am](https://cloud.githubusercontent.com/assets/8633545/14116585/518a1a2e-f595-11e5-9d13-90213e08f941.png)

this is the furthest down you can see in the live preview

**Comment by alexandru-paduraru** [comment]
@nblake989 thank you for pointing out. We were working this week on the other issues from github and we will fix the problem, that you pointed out, in this new update. This should come in 1-2 days. As a quick solution till we release this you can add an extra padding to the sidebar-wrapper. Please add this code at the end of your file:

    .sidebar .sidebar-wrapper{
        padding-bottom: 40px;
    }


Keep in touch,
Alex

**Comment by nblake989** [comment]
Thanks Alex,

That padding is exactly what I did to resolve the issue in the short term. Just wanted to make sure you were aware of the problem. 

-Nick

**Comment by timcreative** [comment]
Now we are aware of it, thanks again for poiting out :D

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Hi @nblake989 this was fixed in v1.2. You can download the update from creative-tim.com

Thank you!
