### ISSUE TITLE
Charts with bottom spacing

### ISSUE THREAD

**Issue by creative-timzye** [timcreative/light-bootstrap-dashboard-pro#7]
When you have a full width card in your code which has a chart inside, there is some space under the card. I don't know, where this extra space comes from.

This is the code:
`<div class="row">`
`    <div class="col-md-12">`
`        <div class="card">`
`            <div class="header">`
`				<h4 class="title">Anzahl Wareneingänge</h4>`
`				<p class="category">Anzahl Wareneingänge pro KW im Jahresvergleich</p>`
`            </div>`
`            <div class="content">`
`	            <div id="weKwVergleich" class="ct-chart ct-perfect-fourth"></div>`
`            </div>`
`            <div class="footer">`
`				<div class="legend">`
`					<i class="fa fa-circle text-info"></i> Wareneingänge <?php echo(date("Y")-1); ?>`
`					<i class="fa fa-circle text-danger"></i> Wareneingänge <?php echo(date("Y")); ?>`
`				</div>`
`            </div>`
`        </div>`
`    </div>`
`</div>`
`<div class="row">`
`    <div class="col-md-12">`
`        <div class="card">`
`            <div class="header">`
`				<h4 class="title">Anzahl Wareneingänge & Artikelmenge</h4>`
`				<p class="category">Anzahl Wareneingänge pro KW im Vergleich zur Artikelmenge</p>`
`            </div>`
`            <div class="content">`
`	            <div id="weKwMengeVergleich" class="ct-chart ct-perfect-fourth"></div>`
`            </div>`
`            <div class="footer">`
`				<div class="legend">`
`					<i class="fa fa-circle text-info"></i> Wareneingänge`
`					<i class="fa fa-circle text-danger"></i> Artikelmenge`
`				</div>`
`            </div>`
`        </div>`
`    </div>`
`</div>`

Then it looks like this:
![lg-app - wareneingang statistik 2016-04-09 13-46-32](https://cloud.githubusercontent.com/assets/17433871/14403516/b02615b6-fe59-11e5-8f56-a360ed08455b.png)

When I have two charts, which are not full width (col-md-6), then there is no additional space at the bottom of the card.

This is the code:
`<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="header">
				<h4 class="title">Anzahl Wareneingänge</h4>
				<p class="category">Anzahl Wareneingänge pro Monat im Jahresvergleich</p>
            </div>
            <div class="content">
	            <div id="weMonatsVergleich" class="ct-chart ct-perfect-fourth"></div>
            </div>
            <div class="footer">
				<div class="legend">
					<i class="fa fa-circle text-info"></i> Wareneingänge <?php echo(date("Y")-1); ?>
					<i class="fa fa-circle text-danger"></i> Wareneingänge <?php echo(date("Y")); ?>
				</div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="header">
				<h4 class="title">Status Wareneingänge</h4>
				<p class="category">Status der Wareneingänge für das 1. Quartal 2016</p>
            </div>
            <div class="content">
	            <div id="weStatusVergleich" class="ct-chart ct-perfect-fourth"></div>
            </div>
            <div class="footer">
				<div class="legend">
					<i class="fa fa-circle text-info"></i> Neu
					<i class="fa fa-circle text-success"></i> In Bearbeitung
					<i class="fa fa-circle text-warning"></i> Abgeschlossen
					<i class="fa fa-circle text-danger"></i> Durchgebucht
				</div>
            </div>
        </div>
    </div>
</div>`

And this is how it looks like:
![lg-app - wareneingang statistik 2016-04-09 13-49-48](https://cloud.githubusercontent.com/assets/17433871/14403527/fe34b0e6-fe59-11e5-90ef-619adeb1d7f0.png)

Any ideas how I can fix this? I have several charts which are full width e.g. col-md-12.

Thanks for your help.

**Comment by alexandru-paduraru** [comment]
@creative-timzye sorry for the late response. I've checked and we couldn't reproduce the behaviour, please check this image:

<img width="1440" alt="screen shot 2016-04-18 at 12 17 59" src="https://cloud.githubusercontent.com/assets/2517758/14599405/cb9206ae-055f-11e6-895a-4aa284d90c39.png">

Can you send us a link to your app? So we can check on the live version and give you a fix.

Best,
Alex

**Comment by creative-timzye** [comment]
Hi Alex,

the code is on intranet, so I can't post an URL. But if you put two col-md-12 charts under each other, then you should be able to reproduce.

If you also change the width of the browser to simulate different display sizes, then you should also see that the size of the space changes with the width of the browser.

If you can't reproduce, I'll attache the entite code,

Thanks,

Jan

**Comment by novamix** [comment]
Hello, sorry my english.
you delete class ct-perfect-fourth

![dashboard html x_lbd_pro_html_v1 2 sublime text hoy at 17 50 55](https://cloud.githubusercontent.com/assets/4966653/14610447/44352ee6-058e-11e6-97d6-e6f3e52a6354.png)

**Comment by alexandru-paduraru** [comment]
@creative-timzye you're right, having 2 x col-md-12 is causing that gap, which is very weird because the header, content and footer of the card are not using that space. Then I've tested the @novamix solution and it is fixing the problem. We will make some more tests with the remove of "ct-perfect-fourth" and if everything is working fine we will remove that default class from all the charts. 

Thank you guys for pointing out and help!

**Comment by alexandru-paduraru** [comment]
I tested for my curiosity and it is working fine with this class: **ct-perfect-twelve** :-))

**Comment by creative-timzye** [comment]
Hi Alex,

I think, there are two possibilities to solve the problem. We either remove the fixed height of ct-charts and use the responsive dimension / ratio classes of chartist.js.

However this might lead to different heights of charts if they are of different kinds, e.g. bar-chart and pie-chart. Which might result in cards of different heights side by side. I have not tested this yet!

The other possibilitiy is to remove the responsive dimension / ratio classes of chartist.js and stick with the fixed height of ct-charts as @novamix suggested.

Thanks for the tips!

Jan

**Comment by JaydeepPatel** [comment]
I am Fresher and Totally New in HTML,

I have this folder **"x_lbd_pro_html_v1.2 3"** So, How can I run the html Project and how can I see this panel ?


Thank x In Advance.

**Comment by alexandru-paduraru** [comment]
Hi Patel,

Thank you for using our product. You need to open any html page in a browser like Google Chrome. We have a tutorial on how to create different elements and pages with LBD Free here: https://www.youtube.com/watch?v=c3M3NQtFyqM <https://www.youtube.com/watch?v=c3M3NQtFyqM>. It’s the same structure of the code and elements.

Please let us know if we can help you with anything else.

Best,
Alex
